### ISSUE TITLE
Space影响cmp补全

### ISSUE THREAD

**Issue by wt-gao** [liubianshi/cmp-lsp-rimels#10]
默认启用`Space`键选择第一候选，但不开启中文输入的时候会覆盖`cmp`补全，很影响写代码的体验。

目前得解决办法是在`Space`回调函数前加个判断：
```lua
local rimels_utils = require("rimels.utils")

local rimels_space = function(fallback)
  -- same as -> require("rimels.cmp_keymaps").keymaps["<Space>"]
  --
end

function user_space(fallback)
  -- rimels disabled
  if not rimels_utils.buf_rime_enabled() then
    return fallback()
  end

  -- rimels enabled
  return rimels_space(fallback)
end

```

最好直接在`Space`回调函数里判断.....

**Comment by liubianshi** [comment]
估计问题来自 `nvim_lsp_signature_help`，我之前感觉到有些不正常，对于自己常用的语言采取了一些临时性措施。

`nvim_lsp_signature_help` 似乎会默认选中候选项，应该是下面这段代码的效果

https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/blob/031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7/lua/cmp_nvim_lsp_signature_help/init.lua#L123

rimels 默认会将选中的候选项上屏，这就导致 `nvim_lsp_signature_help` 生效时，按空格会上屏自动选中的参数。

我现在将 rimels 以外的选中候选项，都用 `fallback()` 处理，您看问题是否已经解决。

**Comment by wt-gao** [comment]
目前没什么问题了。

非常感谢👍👍👍

**Comment by liubianshi** [comment]
不客气😄😄

**Comment by wt-gao** [comment]
`Enter`键被影响了，本来`Enter`上屏的效果没了😅😅

**Comment by liubianshi** [comment]
改回来了😅😅
