### ISSUE TITLE
与 neoconf 共同使用bug

### ISSUE THREAD

**Issue by cxwx** [liubianshi/cmp-lsp-rimels#3]
```
[lspconfig] unhandled error: ....local/share/nvim/lazy/neoconf.nvim/lua/neoconf/util.lua:54: attempt to call upvalue 'ro
ot_dir' (a nil value)
```

**Comment by cxwx** [comment]
似乎是配置rime_ls 的问题，我自己配置的rime_ls 同样的问题

**Comment by cxwx** [comment]
似乎与
```
It's important that you set up neoconf.nvim BEFORE nvim-lspconfig.
```
与lazy的依赖，载入先后相关

**Comment by liubianshi** [comment]
感觉问题应该处在 neoconf.nvim 的配置上。需要在调用 `require('lspconfig').XXXXX.setup()` 前先调用 `require("neodev").setup()`。 

这个插件我当时也折腾了很久才能正常使用，现在是把这两个插件的配置都放在一个[文件](https://github.com/liubianshi/.nvim/blob/3e2a35e33a9f44dd9f5c685a89df3f1e62b6cb0b/Plugins/nvim-lspconfig.lua), 你可以参考一下。

**Comment by cxwx** [comment]
不是 neodev 插件，
是 [neoconf](https://github.com/folke/neoconf.nvim) 插件，

> 感觉问题应该处在 neoconf.nvim 的配置上。需要在调用 `require('lspconfig').XXXXX.setup()` 前先调用 `require("neodev").setup()`。
> 
> 这个插件我当时也折腾了很久才能正常使用，现在是把这两个插件的配置都放在一个[文件](https://github.com/liubianshi/.nvim/blob/3e2a35e33a9f44dd9f5c685a89df3f1e62b6cb0b/Plugins/nvim-lspconfig.lua), 你可以参考一下。

**Comment by liubianshi** [comment]
做了一些修改，在 neoconf 的默认配置下能使用了，你看看是否还有其他问题

**Comment by cxwx** [comment]
fixed
