### ISSUE TITLE
某些符号 如`-，=` 无法在后面打出空格，以及某些不希望的补全没办法避免触发

### ISSUE THREAD

**Issue by baitwo02** [liubianshi/cmp-lsp-rimels#4]
对于某些符号，比如 `"-"， "="` 无论是 `enter` 还是 `空格` 都没办法在它后面打出空格继续输入。(无论是 `enter` 还是 `空格` 按下都没反应，除非继续输入其他东西或者退出输入模式)

以及对于某些并不来自`rime-ls`源的补全, 比如同一个 buffer 的一些 text, 我并不希望触发, 然而无论是 `enter` 还是 `空格` 都会触发补全。 

使用的是lazyvim, 没有做任何额外的配置。

**Comment by liubianshi** [comment]
你说的这两个问题，我这边都没有出现过。可能是因为 cmp-lsp-rimels 和 lazyvim 都改变了按键的行为，而两者中间存在冲突。我没有使用过 lazyvim，所以具体如何排查，也是没有什么头绪

**Comment by baitwo02** [comment]
确实是快捷键冲突了，但是改外快捷键后数字上屏也没有了，很奇怪，相关的快捷键只改了`<enter>`
