### ISSUE TITLE
rime中改配置

### ISSUE THREAD

**Issue by now-ing** [liubianshi/cmp-lsp-rimels#5]
1. 配制的时候，我用的形码，我直接把/Users/mac2/Library/Rime 里面的复制到-- MacOS: /Library/Input Methods/Squirrel.app/Contents/SharedSupport，但是确没有反而不能用了？（本来是能有拼音的补全的，结果就变没了。）

<img width="123" alt="CleanShot2024-07-04at19 49 56@2x" src="https://github.com/liubianshi/cmp-lsp-rimels/assets/24534365/8fc5da2b-35e4-4960-b63b-30a7397fce63">
2. “&” ，             schema_trigger_character = "&", -- [since v0.2.0] 当输入此字符串时请求补全会触发 “方案选单”， 直接用& 然后tab，给出的只是普通的对字符的补全。没有对方案的选择

**Comment by liubianshi** [comment]
这个您可能得去上游（[wlh320/rime-ls](https://github.com/wlh320/rime-ls) 问问了。在我自己的配置上按 `&` 也是毫无反应，我目前不知道如何解决。

我的应对方法是给 rime-ls 单独设置一个配置文件夹，将第一个方案设置为日常使用的方案，之后就不再切换输入法案，全半角字符，简体繁体等。

**Comment by wlh320** [comment]
1. 可以检查一下方案是不是默认英文输入了，这样对于 rime-ls 来说等于没有开启输入法就没法补全。
2. rime-ls 的方案选单现在实现非常简单，就是给 rime 引擎发送一个 F4，所以需要方案里把 F4 作为方案选单的快捷键。

**Comment by liubianshi** [comment]
我在 `lspconfig.rime_ls.setup` 时忘记传递 `schema_trigger_character` 了，加上后，现在应该可以实现了。

![flameshot_20240716111827](https://github.com/user-attachments/assets/2b5690df-26b7-481f-887f-46fc93e7f628)
