### ISSUE TITLE
调用setup后自定义按键被修改

### ISSUE THREAD

**Issue by Kaiser-Yang** [liubianshi/cmp-lsp-rimels#7]
我将rimels放在了nvim-cmp的dependencies部分，但我发现我的`c-n`按键被修改成了触发补全或者是选择下一个补全。但是我在`nvim-cmp`的设置中取消了该按键的设置，后续并将该按键设置成了`esc`，当我注释掉`require'rimels'.setup`后，按键恢复正常。

**Comment by liubianshi** [comment]
看描述似乎是调用 rimels 导致按键配置失效了，我这几天想想怎么解决

**Comment by Kaiser-Yang** [comment]
应该不是`rimels`的问题，因为我现在直接在使用`rime-ls`文档中提供的`nvim-cmp`相关部分的配置，目前使用一切正常，按键没有没重新绑定。

**Comment by liubianshi** [comment]
配置快捷键时没有读取用户的快捷键设置，现在应该改好了
