### ISSUE TITLE
数字自动上屏配合cmp-buffer等不能实现

### ISSUE THREAD

**Issue by Kaiser-Yang** [liubianshi/cmp-lsp-rimels#8]
我查看了源代码，发现数字键自动上屏是通过按下数字键后去触发`0`重新补全实现，也就是下面的代码：

```lua
function M.rimels_auto_upload(entries)
  if #entries == 1 then
    if M.input_method_take_effect(entries[1]) then
      cmp.confirm {
        behavior = cmp.ConfirmBehavior.Insert,
        select = true,
      }
    end
  end
end
M.keymaps["0"] = cmp.mapping(function(fallback)
  if not cmp.visible() or not utils.buf_rime_enabled() then
    return fallback()
  end

  local first_entry = cmp.core.view:get_first_entry()
  if not M.input_method_take_effect(first_entry) then
    return fallback()
  end

  M.rimels_auto_upload(cmp.core.view:get_entries())
end, { "i" })
```

目前发现了两个问题：
1. 假设我需要输入`n0`但是当我输入`n`后第一个补全选项是`你`所以此时`0`会触发`rimels_auto_upload`而由于补全列表长度不为`1`此时的`0`不会被输入。
2. 当配合`cmp-buffer`时，输入数字按键会出现一个`buffer`的补全，如下图所示（在下图中也看见了`cmp-yanky`的补全）:
![image](https://github.com/user-attachments/assets/868a870d-1bd8-4773-849b-52aee6c9b7dc)

我给出的更改建议是：
对于第一条，可以通过为`rimels_auto_upload`增加返回值来判断是否成功触发，当没有成功触发的时候正常插入`0`字符。

对于第二条，可以在`rimels_auto_upload`中判断当前的是否只存在一个`rime-ls`的补全，只要只存在一个`rime-ls`的补全就将其上屏。

**Comment by Kaiser-Yang** [comment]
希望这段代码能提供帮助：

```lua
local function is_rime_entry(entry)
  return vim.tbl_get(entry, "source", "name") == "nvim_lsp"
    and vim.tbl_get(entry, "source", "source", "client", "name")
      == "rime_ls"
end
local function auto_upload_rime()
    if not cmp.visible() then
        return
    end
    local entries = cmp.core.view:get_entries()
    if entries == nil or #entries == 0 then
        return
    end
    local first_entry = cmp.get_selected_entry()
    if first_entry == nil then
        first_entry = cmp.core.view:get_first_entry()
    end
    if first_entry ~= nil and is_rime_entry(first_entry) then
        local rime_ls_entries_cnt = 0
        for _, entry in ipairs(entries) do
            if is_rime_entry(entry) then
                rime_ls_entries_cnt = rime_ls_entries_cnt + 1
                if rime_ls_entries_cnt == 2 then
                    break
                end
            end
        end
        if rime_ls_entries_cnt == 1 then
            cmp.confirm {
                behavior = cmp.ConfirmBehavior.Insert,
                select = true,
            }
        end
    end
end
```

**Comment by liubianshi** [comment]
很好的建议，增加一重判断的确可以解决第一个问题。在修的时候，感觉还是用 `<F31>` 这种正常情况下用不到的键代替 `0` 应该更妥一些，当时选择 `0` 作为辅助按键的做法有点轻率了。

您说的第二条，按理应该不会出现才对。按数字键后，会更根据 first_entry 做判断，如果是 rime_entry，那么应该会自动上屏。比如下面这种情况，我这按数字键 `1` 会自动上屏 `你好`

![image](https://github.com/user-attachments/assets/fae50f22-6c36-446c-b49e-1f69d23957c9)

**Comment by Kaiser-Yang** [comment]
> 很好的建议，增加一重判断的确可以解决第一个问题。在修的时候，感觉还是用 `<F31>` 这种正常情况下用不到的键代替 `0` 应该更妥一些，当时选择 `0` 作为辅助按键的做法有点轻率了。
> 
> 您说的第二条，按理应该不会出现才对。按数字键后，会更根据 first_entry 做判断，如果是 rime_entry，那么应该会自动上屏。比如下面这种情况，我这按数字键 `1` 会自动上屏 `你好`
> 
> ![image](https://private-user-images.githubusercontent.com/24829102/356106736-fae50f22-6c36-446c-b49e-1f69d23957c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTkwMTUsIm5iZiI6MTcyMzA5ODcxNSwicGF0aCI6Ii8yNDgyOTEwMi8zNTYxMDY3MzYtZmFlNTBmMjItNmMzNi00NDZjLWI0OWUtMWY2OWQyMzk1N2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA2MzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YjIyNDlmMzZkZTI2YzFkMTI1M2UxOWJlYjU4MTlhYmNjNTQ2YzRmZmRkNjM5NTJiNWIxODU5ZjViNzQ0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huDLlUagdtsQkptbJrkxN7CBB_XG4ruztTEXRUSL9NE)

这个地方你传入的是所有的 `entries` 所以在有多个候选的时候自动上屏不会触发。
![image](https://github.com/user-attachments/assets/d5a8bbaf-d664-4ed2-b1ce-e0231b4cd6b9)

**Comment by liubianshi** [comment]
是的，确实有这个问题，我根据你前面的代码改下这个函数

**Comment by liubianshi** [comment]
根据 rime 的特性，按数字键后应该不可能出现多个 rime-ls 候选项的情况，感觉可以不用判断只存在一个 rime-ls 补全的情况。

之前之所以加了一个 `#entries == 1` 的条件，当时觉得应该由用户来选择上屏 `nihao1` 还是 `你好`。现在想想，既然开启中文输入，绝大多数时候 `你好` 会是想上屏的内容。之前的做法太保守了。

**Comment by Kaiser-Yang** [comment]
> 根据 rime 的特性，按数字键后应该不可能出现多个 rime-ls 候选项的情况，感觉可以不用判断只存在一个 rime-ls 补全的情况。

这句话不成立，比如双拼模式下输入`nihao2` 可能出现下图情况：
![image](https://github.com/user-attachments/assets/4156364a-6caf-4fc2-b63f-5bc0138a3e33)

也就是在输入后但是选择的部分没有消耗完输入内容的时候可能出现多个候选的情况，就好比输入了很长的字母，然后每次几个词语词语的去选择。

**Comment by liubianshi** [comment]
修了一个版本，应该可以实现了
